from .device import detect_accelerator, select_dtype, configure_backends, get_vram_info
from .model_manager import (
    BASE_DIR,
    MODELS_ROOT,
    LLM_PATH,
    VISION_ENC_PATH,
    OCR_PATH,
    MODEL_SPECS,
    MODEL_KEYS,
    MissingModelError,
    ensure_model_dir,
    get_model_dir,
    get_model_path,
    is_model_ready,
    missing_models,
    check_all_models,
    describe_model,
    format_model_report,
    resolve_siglip2_ref,
    DEFAULT_LANGUAGE,
    LANG_MODEL_KINDS,
    LANG_REPO_TEMPLATES,
    lang_repo_id,
    lang_repo_name,
    lang_model_dir,
    lang_model_ready,
    lang_models_ready,
    missing_lang_models,
    ensure_lang_model_dir,
    describe_lang_model,
    describe_lang_models,
    format_lang_report,
    save_active_language,
    load_active_language,
    active_language_code,
    installed_language_codes,
    STANZA_ROOT,
    STANZA_CORE_PROCESSORS,
    stanza_repo_id,
    stanza_lang_dir,
    stanza_ready,
    describe_stanza,
    format_stanza_report,
    installed_stanza_langs,
)
from .lang_codes import (
    ISO1_TO_ISO3,
    ISO3_TO_ISO1,
    LANGUAGE_NAMES,
    normalize_lang_code,
    language_name,
    iso1_of,
    dominant_script,
    script_histogram,
    candidates_for_script,
    exclusive_language_of,
)
from .language import (
    LanguageDetector,
    LanguageVerdict,
    detect_language,
    detect_language_from_text,
    script_summary,
)
from .scoring import FieldScorer
from .nms import NMSProcessor, Candidate, gumbel_expected_z
from .cropper import RegionCropper

from .registry import ModelRegistry, STEP_REQUIREMENTS, ROLE_LABELS

_LAZY = {
    "AXVEEmbedder": (".embedding", "AXVEEmbedder"),
    "PatchGrid": (".embedding", "PatchGrid"),
    "HayaiOCR": (".ocr", "HayaiOCR"),
    "LanguageModelFetcher": (".model_fetcher", "LanguageModelFetcher"),
    "BaseModelFetcher": (".model_fetcher", "BaseModelFetcher"),
    "ensure_language_models": (".model_fetcher", "ensure_language_models"),
    "resolve_available_language": (".model_fetcher", "resolve_available_language"),
    "probe_language": (".model_fetcher", "probe_language"),
    "probe_repo": (".model_fetcher", "probe_repo"),
    "probe_base_model": (".model_fetcher", "probe_base_model"),
    "StanzaFetcher": (".model_fetcher", "StanzaFetcher"),
    "ensure_stanza_models": (".model_fetcher", "ensure_stanza_models"),
    "probe_stanza": (".model_fetcher", "probe_stanza"),
    "StanzaNLP": (".nlp", "StanzaNLP"),
    "MorphVerdict": (".nlp", "MorphVerdict"),
    "load_stanza": (".nlp", "load_stanza"),
}


def __getattr__(name):
    target = _LAZY.get(name)
    if target is None:
        raise AttributeError(f"module 'core' has no attribute '{name}'")
    import importlib
    mod = importlib.import_module(target[0], __name__)
    value = getattr(mod, target[1])
    globals()[name] = value
    return value


def __dir__():
    return sorted(list(globals().keys()) + list(_LAZY.keys()))


__all__ = [
    "detect_accelerator",
    "select_dtype",
    "configure_backends",
    "get_vram_info",
    "BASE_DIR",
    "MODELS_ROOT",
    "LLM_PATH",
    "VISION_ENC_PATH",
    "OCR_PATH",
    "MODEL_SPECS",
    "MODEL_KEYS",
    "MissingModelError",
    "ensure_model_dir",
    "get_model_dir",
    "get_model_path",
    "is_model_ready",
    "missing_models",
    "check_all_models",
    "describe_model",
    "format_model_report",
    "resolve_siglip2_ref",
    "DEFAULT_LANGUAGE",
    "LANG_MODEL_KINDS",
    "LANG_REPO_TEMPLATES",
    "lang_repo_id",
    "lang_repo_name",
    "lang_model_dir",
    "lang_model_ready",
    "lang_models_ready",
    "missing_lang_models",
    "ensure_lang_model_dir",
    "describe_lang_model",
    "describe_lang_models",
    "format_lang_report",
    "save_active_language",
    "load_active_language",
    "active_language_code",
    "installed_language_codes",
    "STANZA_ROOT",
    "STANZA_CORE_PROCESSORS",
    "stanza_repo_id",
    "stanza_lang_dir",
    "stanza_ready",
    "describe_stanza",
    "format_stanza_report",
    "installed_stanza_langs",
    "StanzaFetcher",
    "ensure_stanza_models",
    "probe_stanza",
    "StanzaNLP",
    "MorphVerdict",
    "load_stanza",
    "ModelRegistry",
    "STEP_REQUIREMENTS",
    "ROLE_LABELS",
    "BaseModelFetcher",
    "probe_base_model",
    "ISO1_TO_ISO3",
    "ISO3_TO_ISO1",
    "LANGUAGE_NAMES",
    "normalize_lang_code",
    "language_name",
    "iso1_of",
    "dominant_script",
    "script_histogram",
    "candidates_for_script",
    "exclusive_language_of",
    "LanguageDetector",
    "LanguageVerdict",
    "detect_language",
    "detect_language_from_text",
    "script_summary",
    "FieldScorer",
    "NMSProcessor",
    "Candidate",
    "gumbel_expected_z",
    "RegionCropper",
    "AXVEEmbedder",
    "PatchGrid",
    "HayaiOCR",
    "LanguageModelFetcher",
    "ensure_language_models",
    "resolve_available_language",
    "probe_language",
    "probe_repo",
]